### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by thecodeduchess** [michelleramsundar/Jammming#1]
**Grade: Meets expectations**

**Summary:** 

I could not build your project. Usually I should not need to do anything beyond navigating to your project in the terminal and running **npm run build**. I reviewed your code and it looked fine for me. 

It seems like you've got a good handle on React syntax. Your consistency with indentations and whitespace made for structured code that made it legible and easy to navigate through.
You followed instructions and have the necessary files for each folder but you've left a lot of overhead for another person to see your work. You are missing a build folder and node_modules, which is why it doesn't work for my computer. 

<img width="655" alt="screen shot 2017-11-04 at 8 58 48 pm" src="https://user-images.githubusercontent.com/8722966/32411196-537909ea-c1a3-11e7-84e4-509283afe726.png">

**Luckily for you, you had the working link live on your Github. I was able to view your project, connect to spotify, search and add tracks.** Good work! Feel free to personalize your page with different fonts, background or design.

Make sure the work you push to Github is ready to be easily cloned and run by another person. :)

**Comment by michelleramsundar** [comment]
Oh, I forgot to add those files but I def have them! :/ THANK YOU!
