### ISSUE TITLE
Saving playlist

### ISSUE THREAD

**Issue by thecodeduchess** [michelleramsundar/Jammming#4]
https://github.com/michelleramsundar/Jammming/blob/fd09c72ea4b9e7b51bceb36a504869436f5dba16/src/Components/PlayList/PlayList.js#L26

I know this works on your hosted version. For my local version, it doesn't actually save due to the discrepancy in the local host addresses and tokens. Not a big issue, I just have to manually change your code to match where I want local host to go. (my local host 3000 is for Rails apps)

**Comment by michelleramsundar** [comment]
Oh, OK. Thanks.
