### ISSUE TITLE
Update Summary

### ISSUE THREAD

**Issue by thecodeduchess** [michelleramsundar/Jammming#5]
**Grade: Meets expectations**

This was a nice attempt on the project and I am so glad to have gotten your project to work on my computer :)

As I mentioned, you have a great knowledge of react and you had the api working properly. 
Feel free to personalize to the app to be your own (font, different background, color scheme).

Good luck on the feature request!

**Comment by michelleramsundar** [comment]
Thank you so much! Looking forward to the last section :)
